name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy Documentation
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Create output directory
        run: mkdir -p ./public

      - name: Generate DocC documentation for main branch
        run: |
          swift package \
            --allow-writing-to-directory ./public/main \
            generate-documentation \
            --target PactKitCore \
            --output-path ./public/main \
            --transform-for-static-hosting \
            --hosting-base-path PactKit/main

      - name: Create redirecting index.html
        run: |
          echo '<!DOCTYPE html>' > ./public/index.html
          echo '<meta http-equiv="refresh" content="0; url=main/documentation/pactkitcore">' >> ./public/index.html

      - name: Create .nojekyll file
        run: touch ./public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
